config/routes.rb
Rails.application.routes.draw do
  resources :team_lists
  resources :user_lists
  resources :admin_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/test', to:'bots#test'
  post '/webhook', to: 'bots#webhook'
end

app/models/user_list.rb
class UserList < ApplicationRecord
end

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController
  before_action :set_user_list, only: [:show, :edit, :update, :destroy]

  # GET /user_lists
  # GET /user_lists.json
  def index
    @user_lists = UserList.all
  end

  # GET /user_lists/1
  # GET /user_lists/1.json
  def show
  end

  # GET /user_lists/new
  def new
    @user_list = UserList.new
  end

  # GET /user_lists/1/edit
  def edit
  end

  # POST /user_lists
  # POST /user_lists.json
  def create
    @user_list = UserList.new(user_list_params)

    respond_to do |format|
      if @user_list.save
        format.html { redirect_to @user_list, notice: 'User list was successfully created.' }
        format.json { render :show, status: :created, location: @user_list }
      else
        format.html { render :new }
        format.json { render json: @user_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_lists/1
  # PATCH/PUT /user_lists/1.json
  def update
    respond_to do |format|
      if @user_list.update(user_list_params)
        format.html { redirect_to @user_list, notice: 'User list was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_list }
      else
        format.html { render :edit }
        format.json { render json: @user_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_lists/1
  # DELETE /user_lists/1.json
  def destroy
    @user_list.destroy
    respond_to do |format|
      format.html { redirect_to user_lists_url, notice: 'User list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_list
      @user_list = UserList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_list_params
      params.require(:user_list).permit(:channel_id, :name, :dual_score)
    end
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/views/user_lists/_form.html.erb
<%= form_with(model: user_list, local: true) do |form| %>
  <% if user_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_list.errors.count, "error") %> prohibited this user_list from being saved:</h2>

      <ul>
      <% user_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.text_field :channel_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dual_score %>
    <%= form.number_field :dual_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_lists/edit.html.erb
<h1>Editing User List</h1>

<%= render 'form', user_list: @user_list %>

<%= link_to 'Show', @user_list %> |
<%= link_to 'Back', user_lists_path %>

app/views/user_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Lists</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Name</th>
      <th>Dual score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_lists.each do |user_list| %>
      <tr>
        <td><%= user_list.channel_id %></td>
        <td><%= user_list.name %></td>
        <td><%= user_list.dual_score %></td>
        <td><%= link_to 'Show', user_list %></td>
        <td><%= link_to 'Edit', edit_user_list_path(user_list) %></td>
        <td><%= link_to 'Destroy', user_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User List', new_user_list_path %>

app/views/user_lists/new.html.erb
<h1>New User List</h1>

<%= render 'form', user_list: @user_list %>

<%= link_to 'Back', user_lists_path %>

app/views/user_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @user_list.channel_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user_list.name %>
</p>

<p>
  <strong>Dual score:</strong>
  <%= @user_list.dual_score %>
</p>

<%= link_to 'Edit', edit_user_list_path(@user_list) %> |
<%= link_to 'Back', user_lists_path %>