config/routes.rb
Rails.application.routes.draw do
  resources :team_lists
  resources :user_lists
  resources :admin_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/test', to:'bots#test'
  post '/webhook', to: 'bots#webhook'
end

app/models/admin_list.rb
class AdminList < ApplicationRecord
end

app/controllers/admin_lists_controller.rb
class AdminListsController < ApplicationController
  before_action :set_admin_list, only: [:show, :edit, :update, :destroy]

  # GET /admin_lists
  # GET /admin_lists.json
  def index
    @admin_lists = AdminList.all
  end

  # GET /admin_lists/1
  # GET /admin_lists/1.json
  def show
  end

  # GET /admin_lists/new
  def new
    @admin_list = AdminList.new
  end

  # GET /admin_lists/1/edit
  def edit
  end

  # POST /admin_lists
  # POST /admin_lists.json
  def create
    @admin_list = AdminList.new(admin_list_params)

    respond_to do |format|
      if @admin_list.save
        format.html { redirect_to @admin_list, notice: 'Admin list was successfully created.' }
        format.json { render :show, status: :created, location: @admin_list }
      else
        format.html { render :new }
        format.json { render json: @admin_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_lists/1
  # PATCH/PUT /admin_lists/1.json
  def update
    respond_to do |format|
      if @admin_list.update(admin_list_params)
        format.html { redirect_to @admin_list, notice: 'Admin list was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_list }
      else
        format.html { render :edit }
        format.json { render json: @admin_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_lists/1
  # DELETE /admin_lists/1.json
  def destroy
    @admin_list.destroy
    respond_to do |format|
      format.html { redirect_to admin_lists_url, notice: 'Admin list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_list
      @admin_list = AdminList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_list_params
      params.require(:admin_list).permit(:channel_id, :name)
    end
end

app/helpers/admin_lists_helper.rb
module AdminListsHelper
end

app/views/admin_lists/_form.html.erb
<%= form_with(model: admin_list, local: true) do |form| %>
  <% if admin_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_list.errors.count, "error") %> prohibited this admin_list from being saved:</h2>

      <ul>
      <% admin_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.text_field :channel_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_lists/edit.html.erb
<h1>Editing Admin List</h1>

<%= render 'form', admin_list: @admin_list %>

<%= link_to 'Show', @admin_list %> |
<%= link_to 'Back', admin_lists_path %>

app/views/admin_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Lists</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_lists.each do |admin_list| %>
      <tr>
        <td><%= admin_list.channel_id %></td>
        <td><%= admin_list.name %></td>
        <td><%= link_to 'Show', admin_list %></td>
        <td><%= link_to 'Edit', edit_admin_list_path(admin_list) %></td>
        <td><%= link_to 'Destroy', admin_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin List', new_admin_list_path %>

app/views/admin_lists/new.html.erb
<h1>New Admin List</h1>

<%= render 'form', admin_list: @admin_list %>

<%= link_to 'Back', admin_lists_path %>

app/views/admin_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @admin_list.channel_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_list.name %>
</p>

<%= link_to 'Edit', edit_admin_list_path(@admin_list) %> |
<%= link_to 'Back', admin_lists_path %>