config/routes.rb
Rails.application.routes.draw do
  resources :team_lists
  resources :user_lists
  resources :admin_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/test', to:'bots#test'
  post '/webhook', to: 'bots#webhook'
end

app/models/team_list.rb
class TeamList < ApplicationRecord
end

app/controllers/team_lists_controller.rb
class TeamListsController < ApplicationController
  before_action :set_team_list, only: [:show, :edit, :update, :destroy]

  # GET /team_lists
  # GET /team_lists.json
  def index
    @team_lists = TeamList.all
  end

  # GET /team_lists/1
  # GET /team_lists/1.json
  def show
  end

  # GET /team_lists/new
  def new
    @team_list = TeamList.new
  end

  # GET /team_lists/1/edit
  def edit
  end

  # POST /team_lists
  # POST /team_lists.json
  def create
    @team_list = TeamList.new(team_list_params)

    respond_to do |format|
      if @team_list.save
        format.html { redirect_to @team_list, notice: 'Team list was successfully created.' }
        format.json { render :show, status: :created, location: @team_list }
      else
        format.html { render :new }
        format.json { render json: @team_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_lists/1
  # PATCH/PUT /team_lists/1.json
  def update
    respond_to do |format|
      if @team_list.update(team_list_params)
        format.html { redirect_to @team_list, notice: 'Team list was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_list }
      else
        format.html { render :edit }
        format.json { render json: @team_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_lists/1
  # DELETE /team_lists/1.json
  def destroy
    @team_list.destroy
    respond_to do |format|
      format.html { redirect_to team_lists_url, notice: 'Team list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_list
      @team_list = TeamList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_list_params
      params.require(:team_list).permit(:channel_id, :team_id, :team_name, :total_score)
    end
end

app/helpers/team_lists_helper.rb
module TeamListsHelper
end

app/views/team_lists/_form.html.erb
<%= form_with(model: team_list, local: true) do |form| %>
  <% if team_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_list.errors.count, "error") %> prohibited this team_list from being saved:</h2>

      <ul>
      <% team_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.text_field :channel_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :team_name %>
    <%= form.text_field :team_name %>
  </div>

  <div class="field">
    <%= form.label :total_score %>
    <%= form.number_field :total_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/team_lists/edit.html.erb
<h1>Editing Team List</h1>

<%= render 'form', team_list: @team_list %>

<%= link_to 'Show', @team_list %> |
<%= link_to 'Back', team_lists_path %>

app/views/team_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Lists</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Team</th>
      <th>Team name</th>
      <th>Total score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_lists.each do |team_list| %>
      <tr>
        <td><%= team_list.channel_id %></td>
        <td><%= team_list.team_id %></td>
        <td><%= team_list.team_name %></td>
        <td><%= team_list.total_score %></td>
        <td><%= link_to 'Show', team_list %></td>
        <td><%= link_to 'Edit', edit_team_list_path(team_list) %></td>
        <td><%= link_to 'Destroy', team_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team List', new_team_list_path %>

app/views/team_lists/new.html.erb
<h1>New Team List</h1>

<%= render 'form', team_list: @team_list %>

<%= link_to 'Back', team_lists_path %>

app/views/team_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @team_list.channel_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @team_list.team_id %>
</p>

<p>
  <strong>Team name:</strong>
  <%= @team_list.team_name %>
</p>

<p>
  <strong>Total score:</strong>
  <%= @team_list.total_score %>
</p>

<%= link_to 'Edit', edit_team_list_path(@team_list) %> |
<%= link_to 'Back', team_lists_path %>